apiVersion: v1
kind: Service
metadata:
  name: info-api-service
spec:
  type: NodePort
  selector:
    app: info-api
    release: v1   # начально будет указывать на первый релиз
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

