apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-api-v4
  labels:
    app: info-api
    release: v4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-api
      release: v4
  template:
    metadata:
      labels:
        app: info-api
        release: v4
    spec:
      containers:
      - name: info-api
        image: info-api:v4
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: RELEASE
          value: "v4"
