apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-api-v5
  labels:
    app: info-api
    release: v5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-api
      release: v5
  template:
    metadata:
      labels:
        app: info-api
        release: v5
    spec:
      containers:
      - name: info-api
        image: info-api:v5
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: RELEASE
          value: "v5"
