apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-api-v3
  labels:
    app: info-api
    release: v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: info-api
      release: v3
  template:
    metadata:
      labels:
        app: info-api
        release: v3
    spec:
      containers:
      - name: info-api
        image: info-api:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: RELEASE
          value: "v3"
